#' Merge duplicated lines into one entry
#'
#' @description Merge duplicated lines into one entry. Useful especially in manipulating files about SNP annotation result generated by snpEff and corresponding downstream analysis, where duplicated entries were generated due to multiple transcripts in one gene or multiple samples in one file. Note: this function may be quite slow when input data is large.
#'
#' @param x a data frame or tibble
#' @param id column index of identical variable, which is used to detect duplication.
#' @param mer column index of variables to merge, default the rest. These columns should only contain numeric values, because merging means simply adding these numbers together.
#'
#' @author Yujie Liu
#' @export
#'
#' @examples
#' x <-
#'   data.frame(
#'     x1 = c("A", "A", "B", "A", "C", "B"),
#'     x2 = c(1, 1, 2, 1, 3, 2),
#'     x3 = c(100, 100, 200, 100, 300, 200),
#'     x4 = c(100, 200, 300, 400, 500, 600)
#'   )
#'
#' merged1 <- mergeDups(x, id = 1)
#' merged2 <- mergeDups(x, id = 1:3)


mergeDups <- function(x, id, mer = -id) {

  dup <- duplicated(x[id])
  x_dup <- x[dup, ]
  x_nodup <- x[!dup, ]

  for (i in 1:nrow(x_dup)) {
    for (j in 1:nrow(x_nodup)) {
      if (sum(x_dup[i, id] == x_nodup[j, id]) == length(id)) {
        x_nodup[j, mer] <- x_nodup[j, mer] + x_dup[i, mer]
      }
    }
  }

  if (class(x_nodup)[1] == "data.frame") {
    rownames(x_nodup) <- 1:nrow(x_nodup)
  }

  return(x_nodup)
}
