#' Merge duplicated lines into one entry
#'
#' @description Merge duplicated lines into one entry. Useful especially in manipulating files about SNP annotation result generated by snpEff, where duplicated entries were generated due to multiple transcripts in one gene.
#'
#' @param x a data frame or tibble
#' @param id column index of identical variable, which is used to detect duplication, default 1
#' @param mer column index of variables to merge, default the rest (2:ncol(x)). These columns should only contain numeric values, because merging means simply adding these numbers together.
#'
#' @author Yujie Liu
#' @export
#'
#' @examples
#' x <-
#'   data.frame(
#'     a = c(1, 2, 3, 2, 3, 2, 4, 5),
#'     b = c(1, 2, 3, 2, 3, 2, 4, 5),
#'     c = c(1, 2, 3, 2, 3, 2, 4, 5),
#'     d = c(1, 2, 3, 2, 3, 2, 4, 5)
#'   )
#'
#' x1 <- mergeDups(x, id = 1, mer = 2)
#' x2 <- mergeDups(x, id = 1, mer = 2:3)
#' x3 <- mergeDups(x, id = 1, mer = c(2,4))



mergeDups <- function(x, id = 1, mer = 2:ncol(x)) {

  dup <- duplicated(x[[id]])
  x_dup <- x[dup,]
  x_nodup <- x[!dup,]

  for (i in 1:nrow(x_dup)) {
    idx <- match(x_dup[i, id], x_nodup[[id]])
    x_nodup[idx, mer] <- x_nodup[idx, mer] + x_dup[i, mer]
  }

  if (class(x_nodup)[1] == "data.frame"){
    rownames(x_nodup) <- 1:nrow(x_nodup)
  }

  return(x_nodup)

}

